### ISSUE TITLE
wrong line in annotation

### ISSUE THREAD

**Issue by emirdemirel** [f90/jamendolyrics#1]
Hi, thanks for this open-source dataset. It's very useful for the evaluation of lyrics related tasks in MIR.

I would like to report an error in the annotations. In the '.words.txt' file for the recording 'Tom_Orlando_-_The_One__feat._Tina_G_', there is a little mistake in line 117. The corresponding lyrics sentence from the raw txt file is :
"You were my first one "
But in the annotation file the word 'one' is written before the word 'first'.

line 114 - you
line 115 - were
line 116 - my
line 117 - one
line 118 - first

Even though it is a minor annotation error, it would be nice to fix it by swapping lines 117 and 188.

Kind regards,

Emir

**Comment by f90** [comment]
Hey, thanks for spotting this. I looked through the whole dataset programmatically to check for correct word order and found another song where a word was swapped. Guess I corrected some things manually in the raw files but forgot to change it in the word list annotation. Should be all fixed now!
