### ISSUE TITLE
Where can I find the training data used?

### ISSUE THREAD

**Issue by yilunzhao** [f90/jamendolyrics#2]
Hi, I really like your work. The result is really impressive.
I am doing research in this field now, and I see in your paper that "For training, we use an internal dataset comprised of 44,232 songs  with English lyrics and varied Western genres such as Pop, Rock and  Hip-Hop." I wonder where can i find this dataset, Thanks!

**Comment by f90** [comment]
Hey, thanks for the compliments, I appreciate it! This work was done during my Spotify internship. Therefore I wasn't able to release that large training dataset you mention to the public, unfortunately. I expect similar performance to be possible when using my approach on the lyrics alignment dataset that was released at ISMIR a few years ago, which features Youtube recordings :)
