### ISSUE TITLE
How to start training a model with my own dataset?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [f90/jamendolyrics#6]
Hi @f90 @vic4code  , thank for sharing the code along with paper, can you please write down a step to step guide on how to use this repo to train a new model? I have a line annotation level dataset.

**Comment by f90** [comment]
Hey, thanks for your interest! I would not recommend training a model on this dataset, as it's too small and you want to reserve these songs for evaluation, to check how well your model works after it has been trained on some other songs.

This repository does not contain any model or training code for a model, so I think you should look at other repositories for that. If you have a line-level annotation dataset, you could look at the following for ready-to-use models and/or training code:

https://github.com/chitralekha18/AutoLyrixAlign
https://github.com/jhuang448/LyricsAlignment-MTL
https://github.com/emirdemirel/Audio2LyricsAlignment_MIREX2019
